trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseJavaVersion@0
  inputs:
    version: '17' # Set the desired Java version
    jdkArchitectureOption: 'x64' # You can change this based on your requirements

- task: UseJavaTool@0
  inputs:
    versionSpec: '17' # Set the desired Java version
    tool: 'JavaTool' # The tool you want to use
    package: 'adopt@1.17' # Package and version of the JDK you want to install
    cleanCache: true # Set this to true to clean the cache

- script: 'echo "##vso[task.setvariable variable=JAVA_HOME]$(JavaTool.JavaTool_17_adopt_1.17.x64)"'
  displayName: 'Set JAVA_HOME'

- script: 'echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME)/bin:$PATH"'
  displayName: 'Add Java to PATH'

- script: |
    # Download Apache Maven
    curl -o apache-maven-3.8.4-bin.tar.gz https://downloads.apache.org/maven/maven-3.8.4-bin.tar.gz

    # Extract Maven
    tar xvzf apache-maven-3.8.4-bin.tar.gz

    # Set MAVEN_HOME
    echo "##vso[task.setvariable variable=MAVEN_HOME]$(Agent.ToolsDirectory)/apache-maven-3.8.4"

    # Add Maven to PATH
    echo "##vso[task.setvariable variable=PATH]$(MAVEN_HOME)/bin:$PATH"
  displayName: 'Install Maven'

- script: 'mvn -version'
  displayName: 'Check Maven Version'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    goals: 'clean install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
