trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "##vso[task.setvariable variable=JAVA_HOME]$(Agent.ToolsDirectory)/jdk/17.0.x64" # Set the desired Java version
    echo "##vso[task.setvariable variable=PATH]$(Agent.ToolsDirectory)/jdk/17.0.x64/bin:$PATH"
  displayName: 'Set Java Version'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    goals: 'install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
