trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseJavaVersion@0
  inputs:
    version: '17' # Set this to the desired Java version

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    goals: 'install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
