trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    # Install Maven Wrapper
    curl -L https://github.com/takari/maven-wrapper/archive/maven-wrapper-0.5.6.tar.gz | tar -xz
    export PATH=$PWD/maven-wrapper-maven-wrapper-0.5.6:$PATH

    # Run Maven using the Wrapper
    ./mvnw -N io.takari:maven:0.7.6:wrapper -Dmaven=3.8.4

    # Run your Maven build
    ./mvnw clean install
  displayName: 'Install and Use Maven Wrapper'

- script: |
    echo "##vso[task.setvariable variable=JAVA_HOME]/usr/lib/jvm/java-17-openjdk-amd64" # Replace with the path to Java 17
    echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME)/bin:$PATH"
  displayName: 'Set JAVA_HOME'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    goals: 'install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
